<a href="https://colab.research.google.com/github/Sridevi-coder62/Numpy-/blob/main/Numpy_Practicals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a NumPy array:

In [69]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


Printing the version

In [70]:
print(np.__version__)

2.1.3


Use a tuple to create a NumPy array:

In [71]:
arr=np.array((1,2,3,4))
print(arr)

[1 2 3 4]


Create a 0-D array with value 42

In [72]:
arr=np.array(42)
print(arr)

42


Create a 1-D array containing the values 1,2,3,4,5:

In [73]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

In [74]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

In [75]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Check how many dimensions the arrays have:

In [76]:
a=np.array(42)
b=np.array([1,2,3,4])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Create an array with 5 dimensions and verify that it has 5 dimensions:

In [77]:
arr=np.array([1,2,3,4,5], ndmin=5)
print(arr, arr.ndim)

[[[[[1 2 3 4 5]]]]] 5


Get the first element from the following array:

In [78]:
arr=np.array([1,2,3,4,5])
print(arr[0])

1


Get the second element from the following array.

In [79]:
print(arr[1])

2


Get third and fourth elements from the following array and add them.

In [80]:
print(arr[2]+arr[3])

7


Access the element on the first row, second column:

In [81]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1])

2


Access the element on the 2nd row, 5th column:

In [82]:
print(arr[1,4])

10


Access the third element of the second array of the first array:

In [83]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


Print the last element from the 2nd dim:

In [84]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])

10


Slice elements from index 1 to index 5 from the following array:

In [85]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


Slice elements from index 4 to the end of the array:

In [86]:
print(arr[4:])

[5 6 7]


Slice elements from the beginning to index 4 (not included):

In [87]:
print(arr[:4])

[1 2 3 4]


Slice from the index 3 from the end to index 1 from the end:

In [88]:
print(arr[-3:-1])

[5 6]


Return every other element from index 1 to index 5:

In [89]:
print(arr[1:5:2])

[2 4]


Return every other element from the entire array:

In [90]:
print(arr[::2])

[1 3 5 7]


From the second element, slice elements from index 1 to index 4 (not included):

In [91]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


From both elements, return index 2:

In [92]:
print(arr[0:2,2])

[3 8]


From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [93]:
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


Get the data type of an array object:

In [94]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int64


Get the data type of an array containing strings:

In [95]:
arr=np.array(['banana','cherry','apple'])
print(arr.dtype)

<U6


In [96]:
arr=np.array([1,2,3,4,5], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


Create an array with data type 4 bytes integer:

In [97]:
arr=np.array([1,2,3,4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


Change data type from float to integer by using 'i' as parameter value:

In [98]:
arr=np.array([1,2,3,4])
new=arr.astype('i')
print(new)
print(new.dtype)


[1 2 3 4]
int32


Change data type from float to integer by using int as parameter value:

In [99]:
arr=np.array([1.1,2.3,5.7,8.0,76.9])
new_arr=arr.astype('i')
print(new_arr)
print(new_arr.dtype)

[ 1  2  5  8 76]
int32


Change data type from integer to boolean:

In [100]:
arr=np.array([12,0,1,0,3])
new_arr=arr.astype(bool)
print(new_arr)
print(new_arr.dtype)


[ True False  True False  True]
bool


NumPy Array Copy vs View

Make a copy, change the original array, and display both arrays:

In [101]:
a=np.array([1,2,3,4,5])
x=a.copy()
a[0]=42

print(a)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


Make a view, change the original array, and display both arrays:

In [102]:
b=np.array([1,2,3,4,5])
y=b.view()

b[0]=3
print(b)
print(y)

[3 2 3 4 5]
[3 2 3 4 5]


Make a view, change the view, and display both arrays:

In [103]:
c=np.array([1,2,3,4,5])
v=c.view()

v[0]=8
print(c)
print(v)

[8 2 3 4 5]
[8 2 3 4 5]


Print the value of the base attribute to check if an array owns it's data or not:

In [104]:
arr=np.array([6,7,8,9,10])

x=arr.copy()
y=arr.view()

print(x.base)
print(y.base)

None
[ 6  7  8  9 10]


Shape of an Array

In [105]:
arr=np.array([[3,4,5,6],[7,8,9,1]])

print(arr.shape)

(2, 4)


Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

In [106]:
arr=np.array([1,2,3,4], ndmin=5)

print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


NumPy Array Reshaping

Convert the following 1-D array with 12 elements into a 2-D array.

The outermost dimension will have 4 arrays, each with 3 elements:

In [107]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Convert the following 1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [108]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(2,3,2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Check if the returned array is a copy or a view:

In [109]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


Convert 1D array with 8 elements to 3D array with 2x2 elements:

In [110]:
arr=np.array([1,2,3,4,5,6,7,8])

print(arr.reshape(2,2,-1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Convert the array into a 1D array:

In [111]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.reshape(-1))

[1 2 3 4 5 6 7 8]


NumPy Array Iterating

Iterate on the elements of the following 1-D array:

In [112]:
arr=np.array([1,2,3,4,5])

for x in arr:
  print(x)

1
2
3
4
5


Iterate on the elements of the following 2-D array:

In [113]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

for x in arr:
  print(x)

[1 2 3 4]
[5 6 7 8]


Iterate on each scalar element of the 2-D array:

In [114]:
arr=np.array([[1,2,3],[4,5,6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


Iterate down to the scalars:

In [115]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


Iterate through the following 3-D array: using nditer

In [116]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


Iterating Array With Different Data Types

Iterate through the array as a string:

In [117]:
arr=np.array([1,2,3,4])
for x in np.nditer(arr, flags=['buffered'], op_dtypes='S'):
  print(x)


np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')


Iterating With Different Step Size

Iterate through every scalar element of the 2D array skipping 1 element:

In [118]:
arr=np.array([[1,2,3],[4,5,6]])

for x in np.nditer(arr[:,::2]):
  print(x)

1
3
4
6


NumPy Joining Array

Join two arrays

In [119]:
arr1=np.array([1,2,3])

arr2=np.array([4,5,6])

arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


Join two 2-D arrays along rows (axis=1):

In [120]:
arr1=np.array([[1,2],[3,4]])

arr2=np.array([[8,9],[11,12]])

arr=np.concatenate((arr1,arr2), axis=1)
print(arr)

[[ 1  2  8  9]
 [ 3  4 11 12]]


Joining Arrays Using Stack Functions

In [121]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr=np.stack((arr1,arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


NumPy provides a helper function: hstack() to stack along rows.

In [122]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


V stack

In [123]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


D stack

In [124]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

arr=np.dstack((arr1,arr2))
print(arr)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


NumPy Splitting Array

Split the array in 3 parts:

In [125]:
arr1=np.array([1,2,3,4,5,6])
new_arr=np.array_split(arr1,3)
print(new_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [126]:
arr1=np.array([1,2,3,4,5,6])
new_arr=np.array_split(arr1,4)
print(new_arr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [127]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


NumPy Searching Arrays


Find the indexes where the value is 4:

In [128]:
arr=np.array([1,2,3,4,5,4,7,4,8,4])

x=np.where(arr==4)
print(x)

(array([3, 5, 7, 9]),)


Find the indexes where the values are odd:

In [129]:
arr1=np.array([3,5,4,2,8,9,15])

x=np.where(arr1%2==1)
print(x)

(array([0, 1, 5, 6]),)


Find the indexes where the values are even:

In [130]:
arr1=np.array([3,5,4,2,8,9,15])

x=np.where(arr1%2==0)
print(x)

(array([2, 3, 4]),)


Search Sorted

In [132]:
arr=np.array([1,2,8,4,9,5])
x=np.searchsorted(arr,5)
print(x)

4


NumPy Sorting Arrays

In [133]:
arr=np.array([7,4,2,9,10,5,3])
print(np.sort(arr))

[ 2  3  4  5  7  9 10]


Sort the array alphabetically:

In [134]:
arr=np.array(['dog','cat','mice','elephant'])
print(np.sort(arr))

['cat' 'dog' 'elephant' 'mice']


Sort a boolean array:

In [135]:
arr=np.array([True,False,False,True,False])
print(np.sort(arr))

[False False False  True  True]


Sort a 2-D array:

In [137]:
arr=np.array([[1,2,6],[9,2,8]])
print(np.sort(arr))

[[1 2 6]
 [2 8 9]]


NumPy Filter Array


Create an array from the elements on index 0 and 2:

In [138]:
arr=np.array([41,44,67,89,23])

x=[True,False,True,False,False]

new=arr[x]
print(new)

[41 67]


In [139]:
arr=np.array([41,23,26,47,49])

filter_arr=[]

for i in arr:
  if i > 41:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

new=arr[filter_arr]

print(filter_arr)
print(new)

[False, False, False, True, True]
[47 49]


Create a filter array that will return only even elements from the original array:

In [140]:
arr=np.array([6,3,9,10,4,8,7,5])

even=[]

for i in arr:
  if i%2==0:
    even.append(True)
  else:
    even.append(False)
new=arr[even]
print(even)
print(new)

[True, False, False, True, True, True, False, False]
[ 6 10  4  8]
